function Fig3a(X, Y1, Y2)
% V_SL and Myoplasmic Ca^2+ vs time
%  X: Time
%  Y1: V_SL (mV)
%  Y2: Myoplasmic Ca^2+ (uM)

%  Auto-generated by MATLAB on 19-Mar-2024 15:49:49

plot1 = figure;
subplot1 = subplot(2,1,1);
hold(subplot1,'on');

plot(X,Y1,'Color',[0.188235294117647 0.819607843137255 0.788235294117647]);
ylabel({'V_{SL} (mV)'},'FontSize',16);

hold(subplot1,'off');
<<<<<<< Updated upstream
set(subplot1,'FontSize',16,'LineWidth',1,'TickDir','none','XGrid','on','XTickLabel','','YTick',[-80 -60 -40 -20 0 20 40]);
=======
set(subplot1,'FontSize',14,'LineWidth',1,'XGrid','on','XTickLabel','','YTick',[-80 -60 -40 -20 0 20 40 60 80]);
>>>>>>> Stashed changes
axes1 = axes('Position',[0.130000000000001 0.239277566539922 0.775 0.347794676806084]);
hold(axes1,'on');

plot(X,Y2,'Color',[0.635294117647059 0.0784313725490196 0.184313725490196]);
ylabel({'[Ca^{2+}]_{myo} (μM)'},'FontSize',16);

xlabel({'Time (s)'},'FontSize',16);
hold(axes1,'off');
set(axes1,'BoxStyle','full','FontSize',16,'GridColor',[0 0 0],'LineWidth',1,'XColor',[0 0 0],'XGrid','on') %,'YTick',[0 5 10 15 20]);
set(plot1,"Renderer","painters");
