function Fig3d(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of semilogy x data
%  YMATRIX1:  matrix of semilogy y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:37:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.100502512562814 0.111486486486486 0.85929648241206 0.813513513513515]);
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(semilogy1(1),'DisplayName','RyR');
set(semilogy1(2),'DisplayName','SERCA');
set(semilogy1(3),'DisplayName','Ca^{2+}_{LeakSR}');

% Create ylabel
ylabel('Ca^{2+} flux (\muM/s)','FontWeight','bold','FontSize',16);

% Create xlabel
xlabel('Time (s)','FontWeight','bold','FontSize',16);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.5]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XTick',[0 0.1 0.2 0.3 0.4 0.5],'YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.80172245499957 0.766340272576628 0.16206029858721 0.152027022747977],...
    'FontSize',14,...
    'EdgeColor','none',...
    'Color','none');

