function Fig3a_2(Time, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:30:22
X1 = Time;
% Create figure
figure1 = figure;
% subplot(3,1,1)
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.144976985825276 0.757488482146769 0.809608812991292]);
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'LineWidth',2,...
    'Color',[0.188235294117647 0.819607843137255 0.788235294117647]);

% Create ylabel
ylabel('V_{SL} (mV)','FontWeight','bold',...
    'Color',[0.196078431372549 0.729411764705882 0.729411764705882]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'LineWidth',2,...
    'Color',[0.635294117647059 0.0784313725490196 0.184313725490196]);

% Create ylabel
ylabel('[Ca^{2+}]_{myo} (\muM)','FontWeight','bold','FontSize',16,...
    'Color',[0.635294117647059 0.0784313725490196 0.184313725490196]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Create xlabel
xlabel('Time (s)','FontWeight','bold','FontSize',16);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.05 0.15]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14);
