function Fig3c(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:44:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0853658536585366 0.11 0.852941176470589 0.815]);
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'LineWidth',2,...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);

% Create ylabel
ylabel('Myoplasmic Ca^{2+} fluxes','FontWeight','bold',...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2000 8000]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'LineWidth',2,...
    'Color',[0.188235294117647 0.819607843137255 0.788235294117647]);

% Create ylabel
ylabel('SR Ca^{2+} fluxes','FontWeight','bold',...
    'Color',[0.196078431372549 0.729411764705882 0.729411764705882]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 450000]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Create xlabel
xlabel('Time (s)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.5]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XTick',[0 0.1 0.2 0.3 0.4 0.5]);
