function Fig3a_1(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:49:49

% Create figure
figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(2,1,1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Color',[0.188235294117647 0.819607843137255 0.788235294117647]);

% Create ylabel
ylabel({'V_{SL}'},'FontWeight','bold','FontSize',16);

hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'LineWidth',1,'TickDir','none','XGrid','on',...
    'XTickLabel','','YTick',[-80 -60 -40 -20 0 20 40 60 80]);
% Create axes
axes1 = axes('Position',...
    [0.130000000000001 0.239277566539922 0.775 0.347794676806084]);
hold(axes1,'on');

% Create plot
plot(X1,Y2,'Color',[0.635294117647059 0.0784313725490196 0.184313725490196]);

% Create ylabel
ylabel({'[Ca^{2+}]_{myo}'},'FontWeight','bold','FontSize',16);

% Create xlabel
xlabel({'Time (s)'},'FontWeight','bold','FontSize',16);

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','FontSize',14,'GridColor',[0 0 0],'LineWidth',1,...
    'XColor',[0 0 0],'XGrid','on','YTick',[0 5 10 15 20]);
