function Fig3e(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:32:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.130620985010707 0.762282958199357 0.794379014989294]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','DHPR');
set(plot1(2),'DisplayName','NCX');

% Create ylabel
ylabel('Ca^{2+} flux (\muM/s)','FontWeight','bold');

% Create xlabel
xlabel('Time (s)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-1708.8948787062 7291.1051212938]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',12.6);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.762577798473114 0.808804951194339 0.159163984838406 0.112419697150939],...
    'FontSize',12.6,...
    'EdgeColor','none',...
    'Color','none');

