function Fig3c(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 19-Mar-2024 15:48:55

% Create figure
figure('OuterPosition',[1289 392 1086 872]);

% Create axes
axes1 = axes('Position',[0.109439252336449 0.111283697047497 0.775 0.815]);
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('p_{Orai1}^{open}','FontWeight','bold','FontSize',16,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);

% Create ylabel
ylabel('[Ca^{2+}]_{SR}','FontWeight','bold','FontSize',16,...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Create xlabel
xlabel({'Time (s)'},'FontWeight','bold');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14);
